---
name: Run Go SDK E2E Tests
on:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.20', '1.21']
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: E2E
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Test
        env:
          EV_APP_UUID: ${{ secrets.EV_APP_UUID_V1 }}
          EV_API_KEY: ${{ secrets.EV_API_KEY_V1 }}
          EV_FUNCTION_NAME: ${{ secrets.EV_FUNCTION_NAME_V1 }}
          EV_INITIALIZATION_ERROR_FUNCTION_NAME: ${{ secrets.EV_INITIALIZATION_ERROR_FUNCTION_NAME }}
          EV_SYNTHETIC_ENDPOINT_URL: ${{ secrets.EV_SYNTHETIC_ENDPOINT_URL }}
        run: go test -v -count=1 -race --tags=e2e ./...
